myName = input("what's your name?: ")
myAge = input("how old are you?: ")
print("damn, you are too young!!")
myCollege = input("ur college name: ")
print("damn, thats a good college!!")
print()
print("so, you are")
print(myName)
print("and are the ripe old age of")
print(myAge)
print("and your college is ")
print(myCollege)

my_variable = input("WHO GOES THERE? ")
print(my_variable)

myGrandma = input("How's your Grandma doing? 😘 ")
print(myGrandma)
#incorrect code
myLunch = input("What are you having for lunch? ")
print("Hmm, it sounds like you really should just order")
print("myLunch")
print("as soon as possible!")
#correct code
myLunch = input("What are you having for lunch? ")
print("Hmm, it sounds like you really should just order")
print(myLunch)
print("as soon as possible!")

#fix my code
print("Definitely not a Phishing Scam")
print()
myName = input("Enter your Name: ")
print("Thanks for logging in")
print(myName)
cardNumber = input("What is your credit card number?")
print("Thanks, I definitely wont put")
print(cardNumber)
print("into Amazon and order anything weird")
print()
print("Promise")
maidenName = input("What is your Mother's maiden name? ")
print()
print("That's cool, I just wanted to know that")
print(maidenName)
print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")
print()
print()
#Challenge Day 2
print("Getting to know you!")
yourName = input("What's your name?: ")
yourFood = input("what's your favourite food?:")
yourMusic = input("what's your favourite music?:")
yourPlace = input("where do you live?:")
print()
print()
print("You are")
print(yourName)
print("You're probably hungry for")
print(yourFood)
print("and you're definitely getting your groove on to")
print(yourMusic)
print("living in the amazing")
print(yourPlace)